import { PanelCard } from '@shared/display/PanelCard';

const currency = (value) => `₹${value.toLocaleString('en-IN')}`;

/**
 * Top contributors — ranked staff sales with proportional bars.
 */
export function TopContributors({ items = [], delay = 0, className }) {
  const max = Math.max(...items.map((item) => item.sales), 1);

  return (
    <PanelCard title="Top Contributors" subtitle="Sales generated by staff" delay={delay} className={className}>
      <ul className="flex flex-col gap-2.5">
        {items.map((item, index) => (
          <li key={item.id} className="animate-fade-up" style={{ animationDelay: `${delay + 120 + index * 90}ms` }}>
            <div className="flex items-center justify-between gap-2 text-xs">
              <span className="truncate font-medium text-content">
                {index + 1}. {item.name}
                <span className="ml-1 text-[11px] font-normal text-content-muted">{item.role}</span>
              </span>
              <span className="shrink-0 tabular-nums text-content">{currency(item.sales)}</span>
            </div>
            <div className="mt-1 h-1.5 w-full overflow-hidden rounded-full bg-accent/15">
              <div
                className="h-full rounded-full bg-accent transition-[width] duration-1000 ease-out"
                style={{ width: `${(item.sales / max) * 100}%`, transitionDelay: `${index * 90}ms` }}
              />
            </div>
          </li>
        ))}
      </ul>
    </PanelCard>
  );
}